global_options:
  freezed:freezed:
    options:
      map:
        map: false
        maybe_map: false
        map_or_null: false
      when:
        when: false
        when_or_null: false
        maybe_when: false
