name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "fastlane/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "fastlane/**"
      - "**.md"

jobs:
  check:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Cache pub packages
        uses: actions/cache@v5
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install grinder
        run: dart pub global activate grinder
      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get
      - name: Auto-format Dart code
        run: dart format lib/
      - name: Commit formatting if needed
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          BRANCH_NAME=${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD)}
          git diff --quiet && echo "No changes" || (git add lib/ && git commit -m "style: auto-format" && git push origin HEAD:$BRANCH_NAME)
      - name: Run code generators
        run: grind gencode genlang
      - name: Check code formatting
        run: grind chkfmt
      - name: Analyze code
        run: grind analyze
      - name: Perform testing
        run: grind test
